DROP TABLE IF EXISTS attendees CASCADE;

CREATE TABLE attendees (
  id SERIAL PRIMARY KEY NOT NULL,
  student_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  session_id INTEGER REFERENCES sessions(id) ON DELETE CASCADE
);