DROP TABLE IF EXISTS poll_cards CASCADE;

CREATE TABLE poll_cards (
  id SERIAL PRIMARY KEY NOT NULL,
  lecture_id UUID REFERENCES lectures(id) ON DELETE CASCADE,
  question VARCHAR(255) NOT NULL,
  position INTEGER NOT NULL
);